LPhistory=new LPhistory_lib;function write_history(a){if(!g_isdebug||!verbose)return!0;if("undefined"==typeof LPhistory||null===LPhistory)LPhistory=new LPhistory_lib;return LPhistory.write(a)}function show_history(){return dump_history()}function clear_history(){return reset_history()}function reset_history(){LPhistory||(LPhistory=new LPhistory_lib);return LPhistory.reset()}function dump_history(){LPhistory||(LPhistory=new LPhistory_lib);return LPhistory.dump()}
function gethistorybuf(){LPhistory||(LPhistory=new LPhistory_lib);return is_user_debug_enabled()?LPhistory.getbuf():""}
function LPhistory_lib(){function a(a){if(!a)return null;var c=a.prop;a=a.dflt;"undefined"==typeof a&&(a=null);var d=c;if("undefined"==typeof c||null===c)d=a;return d}var f=[],k=this;this.write=function(a){if(!g_isdebug||!verbose)return!0;if(!a)return!1;"undefined"==typeof a.timestamp&&(a.timestamp=(new Date).getTime());var c,d=a.tabid,b=a.docnum;"undefined"==typeof a.docnum&&(null!==g_CS_tops&&d)&&(b=g_CS_tops[d]);null!==b&&("undefined"!=typeof b&&d)&&(c="","all"==b?c=ftd_get_topurl(d):(c=getcsinfo(d,
b))&&c.url?c=c.url:g_CS[d]&&g_CS[d][b]?(d=g_CS[d][b],c=gettaburl(d),c||(c=d.name)):c="",a.url=c);!g_isdebug||!verbose?a=!0:(f||(f=[]),a?("undefined"==typeof a.timestamp&&(a.timestamp=(new Date).getTime()),8192<f.length&&f.shift(),f.push(a),a=!0):a=!1);return a};this.getbuf=function(){return k.dump(!0)};this.dump=function(j){var c="";if(!g_isdebug||!verbose)return j?c:!0;if(!f)return console.error("empty history !"),j?c:!1;var d;for(d=0;d<f.length;d++){var b=f[d];if(b){var h="",g=b.timestamp,h="undefined"==
typeof g||null===h?"none?":"undefined"!=typeof(new Date(g)).toUTCString?(new Date(g)).toUTCString():parseInt(g/1E3).toString(),g=a({prop:b.aid,dflt:""}),m=a({prop:b.tabid,dflt:""}),n=a({prop:b.cmd,dflt:"none?"}),p=a({prop:b.url,dflt:""}),q=a({prop:b.msg,dflt:""}),l=a({prop:b.docnum,dflt:""}),r=a({prop:b.docstate,dflt:""}),s=a({prop:b.submit,dflt:"none"}),k=a({prop:b.doconfirm,dflt:"none"}),t=a({prop:b.allowforce,dflt:"none"}),u=a({prop:b.name,dflt:""}),v=a({prop:b.custom_js,dflt:""}),E=a({prop:b.is_launch,
dflt:""}),w=a({prop:b.manualfill,dflt:""}),F=a({prop:b.originator,dflt:""}),x=a({prop:b.delay,dflt:0}),G=a({prop:b.submit_js,dflt:""}),H=a({prop:b.submit_id,dflt:""}),y=a({prop:b.username,dflt:""}),I=a({prop:b.result,dflt:""}),z=a({prop:b.force_fillbest,dflt:"none"}),J=a({prop:b.ready_state,dflt:-1}),K=a({prop:b.status,dflt:-1}),A=a({prop:b.sz,dflt:-1}),L=a({prop:b.status_s,dflt:-1}),B=a({prop:b.lver,dflt:-1}),C=a({prop:b.sver,dflt:-1}),D=a({prop:b.spin,dflt:""});a({prop:b.flavor,dflt:""});a({prop:b.color,
dflt:""});var M=a({prop:b.num,dflt:-1}),b=a({prop:b.file,dflt:""}),e="";switch(n){case "fill_A1":case "fill_A2":case "fill_A3":case "fill_A4":case "FILL_F2":case "FILL_F3":case "FILL_F4":case "FILL_F5":case "FILL_F6":case "fill_PW":case "FILLBASIC":case "autofillaid":case "autologinaid":e=sprintf("[submit=%s][doconfirm=%s][allowforce=%s]",s,k,t);break;case "fillfieldCS":e=sprintf("[name=%s][manualfill=%s][is_launch=%s][originator=%s][delay=%dms][custom_js=%s]",u,w,E,F,x,v);break;case "fillbestCS":e=
sprintf("[username=%s][force_fillbest=%s][custom_js=%s]",y,z,v);break;case "submitCS":e=sprintf("[submit_id=%s][delay=%dms][submit_js=%s]",H,x,G);break;case "check_autologin1":case "check_autologin2":case "check_autologin3":e=sprintf("[dosubmit=%s]",s);break;case "fillfieldconfirm":e=sprintf("[result=%s][manualfill=%s][allowforce=%s][fieldname=%s][force_fillbest=%s]",I,w,t,u,z);break;case "get_accts_success":case "get_accts_fail":e=sprintf("[size=%d][ready_state=%d][status=%d][lver=%d][sver=%d]",
A,J,K,B,C);break;case "get_accts_local":e=sprintf("[size=%d][status=%s][lver=%d][sver=%d]",A,L,B,C);break;case "showchangenotification":e=sprintf("[spin=%s]",D);break;case "showaddnotification":e=sprintf("[spin=%s][username=%s]",D,y);break;case "LoadData":e=sprintf("[file=%s][num=%d]",b,M);break;default:e=""}h=sprintf("[%s][%s]%s%s%s%s%s%s%s",n,h,m?sprintf("[tabid=%s]",m):"",l||0===l?sprintf("[docnum=%s]",l):"",p?sprintf("[url=%s]",p):"",g||0===g?sprintf("[aid=%s]",g):"",q?sprintf("[msg=%s]",q):"",
r?sprintf("[docstate=%s]",r):"",e);j?c=c+h+"\n":console.log(h)}}return j?c:!0};this.reset=function(){f=[];return!0}};
