var KEY_UP=38,KEY_DOWN=40,KEY_ENTER=13,ELEMENT_NODE=1,KEY_ESCAPE=27,KEY_F4=115,KEY_LEFT=37,KEY_RIGHT=39,KEY_HOME=36,KEY_END=35,g_do_complete=!0,g_do_svg=!0;function openCombo(a,e,d,c){c=c?c:document;a=c.getElementById(e);a.disabled||(d=gComboEx=c.getElementById(d),"block"!=d.style.display?showCombo(a,d,null,c):setStyle(d,"display","none",""),gItemNum=-1,gFocusItem=a,("undefined"!=typeof window?window:c.defaultView).setTimeout(function(){doFocus()},0))}
var g_iField=null,g_cb=null,g_combobox_button=null;function showCombo(a,e,d,c){c=c?c:document;g_iField=a;g_cb=e;null!=a&&(e=getComboButtonId(a.id),g_combobox_button=c.getElementById(e),"undefined"!=typeof a.addEventListener?a.addEventListener("move",function(){realShowCombo(c)},!1):a.attachEvent("onmove",function(){realShowCombo(c)}));realShowCombo(c)}function getY(a){for(var e=0;null!=a;)e+=a.offsetTop,a=a.offsetParent;return e}
function getX(a){for(var e=0;null!=a;)e+=a.offsetLeft,a=a.offsetParent;return e}
function realShowCombo(a){null==a&&(a=document);var e=getY(g_iField),d=getX(g_iField),e=e+g_iField.offsetHeight+"px",d=d+"px";g_cb.style.minWidth=g_iField.offsetWidth-14+"px";setStyle(g_cb,"top",e,"");setStyle(g_cb,"left",d,"");setStyle(g_cb,"display","block","");g_combobox_button&&setStyle(g_combobox_button,"display","","");d=LP_getAbsolutePos(a,g_iField);null!=d&&0<d.left&&(a="undefined"!=typeof window&&"undefined"!=typeof window.setTimeout?window:a.defaultView,e=a.innerWidth,null==e&&"undefined"!=
typeof getWindowWidth&&(e=getWindowWidth(a)),null!=e&&0<e&&(g_cb.style.maxWidth=parseInt(e)-parseInt(d.left)-16+"px",parseInt(g_cb.style.maxWidth)<parseInt(g_cb.style.minWidth)&&(g_cb.style.minWidth=g_cb.style.maxWidth)))}var gItemNum=0,gComboEx=null;
function focusCombo(a,e,d){var c=a.keyCode;if("undefined"!=typeof TABKEY&&(c==TABKEY||c==SHIFTKEY)&&-1!=document.location.href.indexOf("popupfilltab.html"))return tabfocuser(a),!1;var b="undefined"!=typeof document?document:a.view.document,c=a.keyCode;a=!0;d=gComboEx=b.getElementById(d);if(c==KEY_DOWN||c==KEY_F4){a=!1;"block"!=d.getAttribute("style.display")&&showCombo(e,d,null,b);e=d.childNodes;c=e.length;for(b=0;null!=e[b]&&b<c;){if(e[b].nodeType==ELEMENT_NODE&&"item"==e[b].className&&"none"!=e[b].style.display){gFocusItem=
e[b];break}b++}gItemNum=b;b>=c&&(gItemNum=0);setTimeout(function(){doFocus()},0);a=!1}else c!=KEY_ENTER&&c==KEY_ESCAPE&&(null!=e.val&&0<e.val.length?a=!0:(a=!1,setStyle(gComboEx,"display","none",""),gItemNum=-1));return a}
function focusItem(a,e,d){a=d.val;for(var c=null,b=getItems(e),j=b.length,h=!1,m=0;m<j;m++)if(b[m].hasChildNodes()&&b[m].firstChild.nodeValue==a){h=!0;c=b[m];gItemNum=m;break}h||(c=addItem(e,a,b.length),gItemNum=b.length);null!=c&&(gFocusItem=c,"block"!=gComboEx.getAttribute("style.display")?(a=d.offsetLeft+"px",setStyle(e,"top",d.offsetTop+d.offsetHeight+"px",""),setStyle(e,"left",a,"")):setStyle(e,"display","none",""),setStyle(e,"display","block",""),setTimeout(function(){doFocus()},0))}
function addItem(a,e,d,c){c||(c=document);var b=c.createElement("div"),j="undefined"!=typeof e.label?e.label:e;b.val="undefined"!=typeof e.label?e.value:e;b.label=j;if("undefined"!=typeof e.label&&(b.label=e.label,"undefined"!=typeof e.image)){var h=c.createElement("img");h.src=e.image;h.style.paddingRight="15px";b.appendChild(h);b.img=h.src}e=c.createTextNode(j);b.appendChild(e);b.setAttribute("tabindex","-1");b.setAttribute("class","item");b.setAttribute("data-lpcount",d);"undefined"!=typeof b.addEventListener?
(b.addEventListener("click",function(){gItemNum=this.getAttribute("data-lpcount")}),b.addEventListener("mouseover",function(){gFocusItem=this;doFocus()})):(b.attachEvent("onclick",function(){gItemNum=this.getAttribute("data-lpcount")}),b.attachEvent("onmouseover",function(){gFocusItem=this;doFocus()}));b.setAttribute("role","listitem");b.setAttribute("origText",ofa(j));a.appendChild(b);return b}
function doComboNav(a,e,d,c){var b=a.keyCode,j=!0;null==gComboEx&&(gComboEx=e);if(b==KEY_UP||b==KEY_DOWN){j=!1;a=0;e=getItems(gComboEx);var h=e.length;if(b==KEY_UP)for(a=gItemNum-1;0<=a&&"none"==e[a].style.display;)"none"==e[a].style.display&&a--;else{a=gItemNum+1;for(a==h&&(a=-1);0<=a&&a<h&&"none"==e[a].style.display;)"none"==e[a].style.display&&a++;a==h&&(a=-1)}gItemNum=a;gFocusItem=-1==gItemNum?c.getElementById(d):e[a];setTimeout(function(){doFocus()},0)}else if(b==KEY_ENTER||!a.keyCode&&0<=a.button){if(e=
getItems(gComboEx),b=e[gItemNum],null!=b&&"true"!=b.getAttribute("aria-disabled")){a=b.label;e=b.val;d=c.getElementById(d);d.value=a;d.val=e;"undefined"!=typeof b.img&&(d.style.background="url("+b.img+") no-repeat 2px 5px",d.style.paddingLeft="25px");if(d.onchange)d.onchange();setStyle(gComboEx,"display","none","");gItemNum=0;gFocusItem=d;setTimeout(function(){doFocus()},0)}}else b==KEY_ESCAPE&&(j=!1,setStyle(e,"display","none",""),gItemNum=0,gFocusItem=c.getElementById(d),setTimeout(function(){doFocus()},
0));return j}function getItems(a){if(null===a)return[];var e=[],e=[];a=a.childNodes;for(var d=a.length,c=0;c<d;c++)if(a[c].nodeType==ELEMENT_NODE&&("item"==a[c].getAttribute("class")||"item focus"==a[c].getAttribute("class")))e[e.length]=a[c];return e}
function setStyle(a,e,d,c){var b=!1;try{a.style&&a.style.setProperty&&(a.style.setProperty(e,d,c),b=!0)}catch(j){alert("exception caught setting style: "+j.message)}if(!b)try{a.style[e]=d,b=!0}catch(h){alert("exception caught setting direct style: "+h.message)}return b}var gFocusItem=null,gLastFocusItem=null;
function doFocus(){null!=gFocusItem&&(gFocusItem.focus(),gLastFocusItem&&"item focus"==gLastFocusItem.className&&(gLastFocusItem.className="item"),gFocusItem&&"item"==gFocusItem.className&&(gFocusItem.className="item focus"),gLastFocusItem=gFocusItem,gFocusItem=null)}
function create_combo(a,e,d,c,b,j,h,m,l){c||(c=document);b||(b="");var f=c.getElementById(a),r=getComboId(a);if(f&&!(c.getElementById(r)||null===r)){f.onkeydown=function(a){return focusCombo(a,f,r)};f.onkeyup=function(a){keyupCombo(c,a,f,r);return!1};f.setAttribute("role","textfield");f.setAttribute("aria-haspopup","true");f.setAttribute("autocomplete","off");f.style.marginRight="0px";var g=c.createElement(b+"div");g.setAttribute("role","list");g.style.display="none";"undefined"!=typeof g_isie&&g_isie&&
(g.style.display="none");g.setAttribute("id",r);g.setAttribute("class","dropStyle");"undefined"!=typeof g_isie&&g_isie&&(g.className="dropStyle");g.onkeydown=function(a){return doComboNav(a,this,this.id.substring(0,this.id.length-6),c)};"undefined"!=typeof g.addEventListener?g.addEventListener("click",function(a){doComboNav(a,this,this.id.substring(0,this.id.length-6),c)}):g.attachEvent("onclick",function(a){doComboNav(a,this,this.id.substring(0,this.id.length-6),c)});g.style.overflowY="auto";g.style.overflowX=
"auto";"undefined"!=typeof g_isie&&g_isie&&(g.style.background="#fff");g.style.paddingLeft="6px";g.style.paddingRight="6px";g.style.position="absolute";g.setAttribute("autofilled","false");l?insertAfter(c.getElementById(l),g):"undefined"!=typeof c.body&&c.body?c.body.appendChild(g):f.parentNode.parentNode.appendChild(g);"undefined"!=typeof f.ownerDocument.defaultView&&"undefined"!=typeof f.ownerDocument.defaultView.addEventListener?(f.ownerDocument.defaultView.addEventListener("click",function(b){b.target.id!=
a&&close_combo(a,c)},!1),f.addEventListener("keydown",function(b){9==b.keyCode&&close_combo(a,c)},!1)):(document.attachEvent("onclick",function(){window.event.srcElement.id!=a&&close_combo(a,c)}),document.attachEvent("onkeydown",function(b){9==b.keyCode&&close_combo(a,c)}));for(l=0;l<e.length;l++)addItem(g,e[l],l,c);e=("undefined"==typeof gLocalBaseUrl?"":gLocalBaseUrl)+"images/pwdrop.png";g_do_svg&&(e=("undefined"==typeof gLocalBaseUrl?"":gLocalBaseUrl)+"images/teardrop.png");if("undefined"!=typeof g_isie&&
g_isie||"undefined"!=typeof g_isfirefox&&g_isfirefox)e="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAfElEQVQ4T2NkoDJgpLJ5DKMGUh6io2GIGobe3t4LGBkZ49FD9v///wu3bt2agC3ECYYhuqH4DANZQNDAgIAAgT9//hwAqtUH4ossLCwOGzZs+IArPRA0EKQRZOjv378nsLKyFuAzjCgXkpoyiXIhKYaOGkhKaGFXS/UwBABG2SEVsoLJ9AAAAABJRU5ErkJggg==";if(d&&"undefined"!=typeof LP_getAbsolutePos){var s=0,p=0,g=c.createElement(b+"div");"undefined"!=typeof c.body&&c.body?j?insertAfter(c.getElementById(j),g):c.body.appendChild(g):
f.parentNode.appendChild(g);var k=getComboButtonId(a);d=[];var q=3,u;u="undefined"!=typeof f.ownerDocument.defaultView&&"undefined"!=typeof f.ownerDocument.defaultView.getComputedStyle?f.ownerDocument.defaultView.getComputedStyle(f):f.currentStyle;b=LP_getAbsolutePos(c,f);if(null!=b&&0<b.left&&0<b.top){var t;t=b.left+parseInt(b.width)+4-30;p=s=0;"undefined"!=typeof g_isie&&g_isie&&(p=-4,s=2);d.left=t+p+"px";d.position="absolute";d.top=parseInt(b.top)+4+s+"px";if("undefined"==typeof g_isfirefox||!g_isfirefox)d.padding=
q+"px"}var n=Math.floor((30-b.height)/2);if(1<=n&&30>b.height&&(p=s=0,d=[],d.position="absolute",d.height=b.height-4+"px",d.width=b.height-4+"px",d.top=parseInt(b.top)+4+n+4+"px",t=b.left+parseInt(b.width)+4-30+n+4,d.left=t+n+"px",q-=2*n,0>q&&(q=0),"undefined"==typeof g_isfirefox||!g_isfirefox))d.padding=q+"px";n=Math.round((b.height-30)/2);if(30<b.height&&(p=s=0,"undefined"!=typeof g_isie&&g_isie&&(d=parseInt(u.borderTopWidth),p=parseInt(u.borderBottomWidth),n-=(d+p)/2,p=-5,s=d),d=[],d.left=t+p+
"px",d.position="absolute",d.top=b.top+n+s+"px",q+=2*n,"undefined"==typeof g_isfirefox||!g_isfirefox))d.padding=q+"px";"undefined"!=typeof g_isie&&g_isie&&(d.border="0px");f.style.textOverflow="ellipsis";f.style.whiteSpace="nowrap";j&&(g.style.marginLeft=h?h+"px":"-15px",g.style.display="inline",g.style.verticalAlign="top",g.style.marginTop="6px",m?(d=[],d.marginTop=m+"px"):d.marginTop="-18px");j="<img id='"+k+"' src='"+e+"' valign='middle'/>";g.innerHTML="undefined"!=typeof g_isfirefox&&g_isfirefox?
xulize(j):j;k=c.getElementById(k);for(l in d)d.hasOwnProperty(l)&&(k.style[l]=d[l]);k.onclick=function(a){openCombo(a,this.id.substring(0,this.id.length-7),getComboId(this.id.substring(0,this.id.length-7)),c);null!=a?a.cancelBubble=!0:window.event.cancelBubble=!0}}else!d&&"undefined"!=typeof LP_getAbsolutePos&&(k=c.createElement(b+"img"),k.id=getComboButtonId(a),null!==k.id&&(k.onclick=function(a){openCombo(a,this.id.substring(0,this.id.length-7),getComboId(this.id.substring(0,this.id.length-7)),
c);null!=a?a.cancelBubble=!0:window.event.cancelBubble=!0}),k.setAttribute("src",e),k.setAttribute("valign","middle"),"undefined"!=typeof g_isopera&&g_isopera&&(k.style.position="relative",k.style.top="7px"),"undefined"!=typeof c.body&&c.body?c.body.appendChild(k):c.getElementById("main").appendChild(k),b=LP_getAbsolutePos(c,f),null!=b&&(0<b.left&&0<b.top)&&(t=b.left+b.width+2,k.style.left=t+"px",k.style.position="absolute",k.style.top=b.top+"px"),n=Math.floor((30-b.height)/2),1<=n&&30>b.height&&
(k.style.height=b.height+"px",k.style.width=b.height+"px",k.style.top=b.top+n+"px"),n=Math.round((b.height-30)/2),30<b.height&&(k.style.top=b.top+n+"px"));k.className+="teardrop"}}function delete_combo_item(a,e){var d=getComboId(a);if(d=document.getElementById(d))for(var c=getItems(d),b=0;b<c.length;b++)if(c[b].innerHTML==e){for(c.splice(b,1);d.hasChildNodes();)d.removeChild(d.firstChild);for(b=0;b<c.length;b++)addItem(d,c[b].innerHTML,b);break}}
function close_combo(a,e){e||(e=document);var d=getComboId(a);if(d=e.getElementById(d))"block"==d.style.display&&(setStyle(d,"display","none",""),gItemNum=-1),g_do_complete&&unhighlight_combo_all_items(e,a)}function repopulate_combo(a,e,d){d||(d=document);var c=getComboId(a);if(c=d.getElementById(c)){for(;c.hasChildNodes();)c.removeChild(c.firstChild);for(var b=0;b<e.length;b++)addItem(c,e[b],b,d)}a=getComboButtonId(a);(d=d.getElementById(a))&&setStyle(d,"display","","")}
function destroy_combo(a,e){e||(e=document);if(!(null==a||0>=a.length))try{var d=getComboId(a),c=e.getElementById(d);if(c){for(;c.hasChildNodes();)c.removeChild(c.firstChild);c.parentNode.removeChild(c)}var b=getComboButtonId(a),j=e.getElementById(b);j&&j.parentNode.removeChild(j)}catch(h){console.log("destroy_combo error: "+h.message)}}function highlight_combo_item(){return 0}function unhighlight_combo_item(){return 0}function unhighlight_combo_all_items(){return 0}
function getComboId(a){return null===a||""===a?null:a+"_combo"}function getComboButtonId(a){return null===a||""===a?null:a+"_button"}function hide_combo_item(a){null!==a&&setStyle(a,"display","none","")}function show_combo_item(a){null!==a&&setStyle(a,"display","","")}function show_all_combo_items(a,e){a||(a=document);if(!(null==e||0>=e.length)){var d=getComboId(e);if(d=a.getElementById(d))for(var d=getItems(d),c=0;c<d.length;c++)show_combo_item(d[c])}}
function combo_filter(a,e,d){a||(a=document);if(!(null===e||0>=e.length)){var c=!0,b=0;null===d&&(d="");var j=of(d,a),h=null,m=getComboId(e);if(m=a.getElementById(m)){for(var l=getItems(m),f=0;f<l.length;f++){var r="undefined"!=typeof g_isfirefox&&g_isfirefox?l[f].textContent:get_innertext(l[f]);""===d.trim()||0<=r.trim().toLowerCase().indexOf(j.toLowerCase())?(show_combo_item(l[f]),highlight_combo_item(a,e,l[f],d),c=!1,b++,h=l[f]):(hide_combo_item(l[f]),unhighlight_combo_item(a,e,l[f]))}if(c)close_combo(e,
a);else if(d=m.getAttribute("autofilled"),1===b&&"false"==d){m.setAttribute("autofilled","true");if(c=a.getElementById(e))b=c.value.length,d=h.val.length,c.value=h.val,"selectionStart"in c?(c.selectionStart=b,c.selectionEnd=d):(h=c.createTextRange(),h.moveStart("character",b),h.collapse(),h.moveEnd("character",d),h.select());close_combo(e,a)}}}}
function keyupCombo(a,e,d,c){a||(a=document);c=a.getElementById(c);if(null!==c&&null!==d){var b=e.keyCode;if(!(b==KEY_DOWN||b==KEY_F4||b==KEY_UP||b==KEY_ENTER||b==KEY_ESCAPE)){if("undefined"!=typeof TABKEY&&(b==TABKEY||b==SHIFTKEY)&&-1!=document.location.href.indexOf("popupfilltab.html"))return tabfocuser(e),!1;isComboShowing(c)||(showCombo(d,c,null,a),gItemNum=-1,setTimeout(function(){doFocus()},0));combo_filter(a,d.id,d.value)}}}function keydownCombo(){}
function isComboShowing(a){return null===a?!1:"block"==a.style.display}function insertAfter(a,e){a.parentNode.insertBefore(e,a.nextSibling)};
